jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - continue-on-error: true
      name: Test Build
      run: 'cd website/

        npm i

        npm run build

        '
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - continue-on-error: true
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      name: Add key to allow access to repository
      run: 'mkdir -p ~/.ssh

        ssh-keyscan github.com >> ~/.ssh/known_hosts

        echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa

        chmod 600 ~/.ssh/id_rsa

        cat <<EOT >> ~/.ssh/config

        Host github.com

        HostName github.com

        IdentityFile ~/.ssh/id_rsa

        EOT

        '
    - continue-on-error: true
      env:
        GIT_USER: git
        USE_SSH: true
      name: Release to GitHub Pages
      run: 'git config --global user.email "yogevbd@wix.com"

        git config --global user.name "yogevbd"

        cd website/

        npm i

        npm run build

        npx docusaurus deploy

        '
name: documentation
on:
  repository_dispatch:
    types: trigger-ga___documentation.yml
