jobs:
  enforce-label:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: yogevbd/enforce-label-action@2.2.2
      with:
        REQUIRED_LABELS_ANY: 'type: accepted/bug,type: accepted/enhancement,Infrastructure,type:
          documentation,skip-changelog'
name: Enforce PR label
on:
  repository_dispatch:
    types: trigger-ga___enforce-label.yml
